cloud_drive_homepage:
    path:     /{path}
    defaults: { _controller: CloudDriveBundle:Default:index, path: '' }
    requirements:
        path: '^[\w:!]+'
cloud_drive_api_main_page:
    path: /api/main/{path}
    defaults: { _controller: CloudDriveBundle:Api:mainPage, path: '' }
    requirements:
        path: '^[\w:!]+'
