cloud_drive_homepage:
    path:     /
    defaults: { _controller: CloudDriveBundle:Default:index, path: '' }
cloud_drive_user_homepage:
    path:     /user/{path}
    defaults: { _controller: CloudDriveBundle:Default:index, path: '' }
    requirements:
        path: '^[\w:!]+'
cloud_drive_api_main_page:
    path: /api/main/{path}
    defaults: { _controller: CloudDriveBundle:Api:mainPage, path: '' }
    requirements:
        path: '^[\w:!]+'
cloud_drive_api_upload:
    path: /api/upload/{path}
    defaults: { _controller: CloudDriveBundle:Api:upload, path: '' }
    requirements:
        path: '^[\w:!]+'
cloud_drive_api_upload_progress:
    path: /api/uploadprogress/
    defaults: { _controller: CloudDriveBundle:Api:uploadProgress}
cloud_drive_api_create_folder:
    path: /api/create/folder/{path}/{name}
    defaults: { _controller: CloudDriveBundle:Api:createFolder }
    requirements:
        path: '^[\w:!]+'
        name: '^[\w_]+'