cloud_drive_homepage:
    path:     /
    defaults: { _controller: CloudDriveBundle:Default:index }
cloud_drive_user_page:
    path: /drive/{userName}
    defaults: { _controller: CloudDriveBundle:Default:user }
    requirements:
        userName: '^[\w]+'
