cloud_drive_homepage:
    path:     /
    defaults: { _controller: CloudDriveBundle:Default:index, path: '' }
cloud_drive_user_homepage:
    path:     /user/{path}
    defaults: { _controller: CloudDriveBundle:Default:index, path: '' }
    requirements:
        path: '^[\w:!]+'
cloud_drive_api_main_page:
    path: /api/main/{path}
    defaults: { _controller: CloudDriveBundle:Api:mainPage, path: '' }
    requirements:
        path: '^[\w:!]+'
cloud_drive_api_upload:
    path: /api/upload/{path}
    defaults: { _controller: CloudDriveBundle:Api:upload, path: '' }
    requirements:
        path: '^[\w:!]+'
cloud_drive_api_upload_progress:
    path: /api/uploadprogress/
    defaults: { _controller: CloudDriveBundle:Api:uploadProgress}
cloud_drive_api_create_folder:
    path: /api/create/folder/{path}/{name}
    defaults: { _controller: CloudDriveBundle:Api:createFolder }
    requirements:
        path: '^[\w:!]+'
        name: '^[\w_]+'
cloud_drive_api_download:
    path: /api/download/{path}/{type}
    defaults: { _controller: CloudDriveBundle:Api:download }
    requirements:
        path: '^[\w:!.-]+'
        type: '^[\w]+'
cloud_drive_api_rename:
    path: /api/rename/{path}/{newName}
    defaults: { _controller: CloudDriveBundle:Api:rename }
    requirements:
        path: '^[\w:!.-]+'
        newName: '^[\w:!.-]+'
cloud_drive_api_delete:
    path: /api/delete/{path}
    defaults: { _controller: CloudDriveBundle:Api:delete }
    requirements:
        path: '^[\w:!.-]+'
cloud_drive_api_open_image:
    path: /api/open/image/{path}
    defaults: { _controller: CloudDriveBundle:Api:openImage }
    requirements:
        path: '^[\w:!.-]+'