<?php

namespace CloudDriveBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CloudDriveBundle\Entity\User;

/**
 * ShareLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareLinkRepository extends EntityRepository
{
    public function getLink($path, $user) {
        /* @var User $user */
        $date = new \DateTime();
        $date->modify('-2 hours');

        return $this->createQueryBuilder('l')
            ->andWhere('l.path = :path')
            ->andWhere('l.user = :user')
            ->andWhere('l.date >= :date')
            ->setParameter('path', $path)
            ->setParameter('user', $user->getId())
            ->setParameter('date', $date->format('Y-m-d H-i-s'))
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

    public function getOpenLink($link) {
        /* @var User $user */
        $date = new \DateTime();
        $date->modify('-2 hours');

        return $this->createQueryBuilder('l')
            ->andWhere('l.link = :link')
            ->andWhere('l.date >= :date')
            ->setParameter('link', $link)
            ->setParameter('date', $date->format('Y-m-d H-i-s'))
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
